[project]
name = "salud-agenda"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.18.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "factory-boy>=3.3.3",
    "psycopg[binary,pool]>=3.3.5",
    "pytest-django[django]>=4.14.0",
    "python-dotenv>=1.2.3",
]

[tool.pytest]
DJANGO_SETTINGS_MODULE = "salud_agenda.settings"
python_files = ["tests.py", "tests_*.py", "test_*.py", "*_tests.py",]
norecursedirs = [".venv", "dist", "*/migrations/"]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "ruff>=0.16.7",
]

[tool.ruff]
line-length = 125
indent-width = 4

[tool.ruff.format]
exclude = ["*.pyi"]
quote-style = "double"
line-ending = "auto"

[tool.ruff.lint]
select = ["E", "I"]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["E501"]
